### ISSUE TITLE
Get-ZertoRecoveryReport failing to pass vpgName and vpgIdentifier parameters correctly

### ISSUE THREAD

**Issue by royminton** [ZertoPublic/ZertoApiWrapper#60]
## Expected Behavior
Get-ZertoRecoveryReport returns data scoped to the VPG passed via the vpgName or vpgIdentifier parameters. It also is not accepting pipeline input.

## Current Behavior
Get-ZertoRecoveryReport fails to return data using the -vpgName parameter or returns unfiltered data when using the -vpgIdentifier parameter. 

## Steps to Reproduce (for bugs)
After a successful 'Connect-ZertoServer':

```
PS C:\> Get-ZertoRecoveryReport -vpgName "VPG_Name" -Verbose
VERBOSE: GET https://ZertoServer:9669/v1/reports/recovery?vpgName=VPG_Name with 0-byte payload
VERBOSE: received 2-byte response of content type application/json; charset=utf-8
```
Running Get-ZertoRecoveryReport with the -vpgIdentifier parameter does not appear to filter the results at all
```
PS C:\> $reports1 = Get-ZertoRecoveryReport -vpgIdentifier "vpgID"
PS C:\> $reports2 = Get-ZertoRecoveryReport
PS C:\> $reports1.count
169
PS C:\> $reports2.count
169
```

## Context
We would like to be able to use this data to report on failover testing and recovery operations.

## Your Environment
Module version: 1.3.0.20191201
Operating System and PowerShell version: Windows 2016 with PS 5 and 6, also Windows 10 with PS 5, 6 and 7
Zerto Virtual Manager Version: 7.5U1

**Comment by wcarroll** [comment]
Hi @royminton 

First, the `-vpgIdentifier` parameter is a mistake. It turns out that the API Endpoint does not support this as a filter. As it does not recognize the filter option, the API discards the filter and does not process it. I will remove this parameter from the function.

Second, for the issue with the `-vpgName` parameter I am unable to duplicate your results with a valid VPG Name. I get the same results if I use a VPG Name that never existed or does not have any reports.

```PowerShell
[59ms] D:\>Get-ZertoRecoveryReport -vpgName "Desktop2" -Verbose
VERBOSE: GET https://192.168.10.20:9669/v1/reports/recovery?vpgName=Desktop2 with 0-byte payload
VERBOSE: received 2721-byte response of content type application/json
VERBOSE: Content encoding: utf-8

General
-------
@{EndTime=11/4/2019 10:49:49 PM; InitiatedBy=vmware; Notes=; PointInTime=11/4/2019 10:47:27 PM; ProtectedSiteName=WCHL… 
@{EndTime=11/4/2019 10:46:30 PM; InitiatedBy=vmware; Notes=; PointInTime=1/1/0001 8:00:00 AM; ProtectedSiteName=WCHL -… 
[84ms] D:\>Get-ZertoRecoveryReport -vpgName "DoesNotExist" -Verbose
VERBOSE: GET https://192.168.10.20:9669/v1/reports/recovery?vpgName=DoesNotExist with 0-byte payload
VERBOSE: received 2-byte response of content type application/json
VERBOSE: Content encoding: utf-8
[466ms] D:\>
```

Would you be able to test again with a different VPG Name and see if you get the same results? I'm also wondering if you get similiar results if you take PowerShell out of the equation and query directly from something like Postman.

Please let me know your thoughts.

Thanks,
Wes

**Comment by royminton** [comment]
@wcarroll Thanks for taking a look. I'm not sure what's changed on my end but I'm having trouble recreating the issue now. I'm going to close this and appreciate you taking a look.
