### ISSUE TITLE
Get-vavpg - Does not return all VPG's

### ISSUE THREAD

**Issue by adminthrivedev** [ZertoPublic/ZertoApiWrapper#64]
According to the documentation, get-zavpg without any parameters is supposed to turn all VPGs but it does not.  In fact, it returns a random VPG.  Also, when I add -zorgidentifier with a proper org id, I get the same result (some random VPG).  On the plus side, if I enter a correct vpgidentifier that does in fact work.

I tried my best to replicate the behavior on the api doc site and it works there.

**Comment by wcarroll** [comment]
@adminthrivedev 

Thanks for reaching out. Something that may be a bit confusing is that the `Get-ZAVpg` function also returns additional data with the list of VPGs. Due to the default formatting output in PowerShell this may not be apparent. The data that is expected to be returned is as follows:

- VPGs (An array of VPGs in the account or zOrg)
- healthyVpgsCount (Number of healthy VPGs in the account or zOrg)
- warnedVpgsCount (Number of VPGs in a warning state in the account or zOrg)
- erroneousVpgsCount (Number of VPGs in an error state in the account or zOrg)

If you are only interested in the VPGs and none of the additional stats, you can do something like this: `Get-ZAVpg | Select-Object -ExpandProperty vpgs` This will display all VPGs in the account.

I will see what I can do to make the documentation clearer for this topic.

Please let me know your thoughts or if you have additional questions.

Thanks,
Wes

**Comment by adminthrivedev** [comment]
This is great, thank you for the clarification.  I knew it had to be something relatively simple that I was missing.
